using UnityEngine;

/// <summary>
/// A module is a plug-in for the character that allows it to do things, such as
/// move and attack. 
///
/// <br/>
///
/// Authors: Ryan Chang (2023)
/// </summary>
public class Module : MonoBehaviour
{
    #region Variables
    #region User Settings

    #endregion

    #region Autogenerated

    #endregion
    #endregion

    #region Properties
    /// <summary>
    /// The <see cref="Character"/> that this is attached to.
    /// </summary>
    public Character Master { get; private set; }
    #endregion

    #region Methods
    #region Instantiation

    #endregion

    #region Main Loop

    #endregion

    #region Public Methods
    public void LinkToMaster(Character master)
    {
        Master = master;
        OnLinked();
    }

    /// <summary>
    /// Called once <see cref="Master"/> is set.
    /// </summary>
    protected virtual void OnLinked() { }
    #endregion

    #region Helper Methods

    #endregion
    #endregion
}