using System;
using System.Collections;
using System.Collections.Generic;
using NaughtyAttributes;
using UnityEngine;

public class FirePillar : MonoBehaviour
{
    #region Variables
    #region User Settings
    public float lifetime = 2;   
    #endregion

    #region Autogenerated
    [SerializeField]
    [ReadOnly]
    private AudioSource flameAudio;
    #endregion
    #endregion

    private void Awake()
    {
        flameAudio = GetComponent<AudioSource>();
        flameAudio.Play();

        SnapToFloor();

        Destroy(gameObject, lifetime);
    }

    private void SnapToFloor()
    {
        var hit = Physics2D.Raycast(
            transform.position + Vector3.up * 10,
            Vector3.down,
            20,
            LayerExt.CreateMask(
                LayersManager.Player,
                LayersManager.Ground,
                LayersManager.Platform
            )
        );

        if (hit)
        {
            transform.position = hit.point;
        }
    }
}
